include $(dir $(abspath $(firstword $(MAKEFILE_LIST))))cc.mk

.PHONY : all

all: v8

#mozjs:
#	$(info SPIDERSHIM: mozjs)
#	$(MAKE) -f spidermonkey.mk

v8:
	$(info SPIDERSHIM: v8)
	$(info SPIDERSHIM: MOZ_OUT=$(MOZ_OUT))

